name: pytest

on:
  push:
    branches:
      - 'main'
      - $default-branch
  pull_request:
  workflow_dispatch:
  schedule:
    # every second day of month at 8:17
    - cron: '17 8 2 * *'

permissions:
  contents: read

jobs:
  latest:
    name: Run Pytests

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.14
      uses: actions/setup-python@v5
      with:
        python-version: '3.14'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        python -m pip install -e .
    - name: Test
      run: |
        python -m pytest -s
